name: macOS

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (Xcode)
        run: cmake -S . -B build -GXcode

      - name: Build Debug
        run: cmake --build build --config Debug

      - name: Build Release
        run: cmake --build build --config Release
